### ISSUE TITLE
Bełkot o LFP w introduction

### ISSUE THREAD

**Issue by szymtor** [szymtor/locfin#6]
Hej,

napisałem coś o LFP. Oryginalnie pisałem dużo więcej, ale był to wielki bełkot, więc zostawiłem to, co jest teraz. Przy okazji, zrobiłem jakieś małe zmiany w tym co pisał Bartek (tu https://github.com/szymtor/locfin/commit/fc48ddcbf3d3880c01bcaaf8809fc48ec74e0e2b jest diff)
– głównie w przykładzie CFI. 

Co Wy na to?

**Comment by szymtor** [comment]
Aha – taka uwaga ogólna. Diff działa wierszami, dlatego warto jest (ręcznie) łamać wiersze w latexu,
żeby nie pisać całego akapitu w jednym wierszu – bo wtedy zmiana jednej litery zaznacza w diffie cały akapit.

**Comment by bklin** [comment]
On 5 Jan 2015, at 20:06, Szymon Toruńczyk wrote:

> Hej,
> 
> napisałem coś o LFP. Oryginalnie pisałem dużo więcej, ale był to wielki bełkot, więc zostawiłem to, co jest teraz. Przy okazji, zrobiłem jakieś małe zmiany w tym co pisał Bartek (tu fc48ddc jest diff)
> – głównie w przykładzie CFI.
> 
> Co Wy na to?

Zastanawiam sie, czy to o LFP nie jest zbyt zaawansowane na Introduction. Może by przenieść to wszystko, razem z moim przykładem CFI, do osobnej sekcji umieszczonej po Asizacji a przed algebra? A w Intro napisać tylko coś krótkiego, że

"squashing relies on atom ordering and from certain points of view this is problematic, for example in descriptive complexity; we give more details in Section ??; and algebraic theory of locally finite templates turns out to work well anyway, so what the hell, we do it because we can"

?

W ten sposób umozliwilibysmy czytelnikowi przeczytanie sporej czesci pracy bez angazowania sie w dubious motivation, no i oszczedzilibysmy mu nieco technikaliow we wstepie.


A co do przykładu z CFI, to skasowales jego koncowke. Czy dlatego ze byla bledna? Na razie dodalem ja z powrotem, razem z rysunkiem jaki mimo wszystko udalo mi sie skonstruowac w xy.

**Comment by ochremiak** [comment]
Hej!

Przepraszam Was, ale ja siedzę nad prezentacją na piątek. Postaram się
jutro rzucić na to wszystko okiem.

Pozdrawiam,
Asia

2015-01-05 20:44 GMT+01:00 bklin <notifications@github.com>:

**Comment by bklin** [comment]
Spróbowałem jednak zostawić LFP w introduction; w tym celu trochę pozmieniałem (idea: uprościłem, a jak wyszło to nie wiem) to co napisał Szymon.

Szymku, zerknij szczególnie na Twój przykład o IBC, chyba jest dobrze ale sprawdzić trzeba.

I uwaga (fanfary!): spushowałem to w nowy branch "intro". Mam nadzieję że się udało i nie zepsułem całego repozytorium.

Jeśli Wam się to spodoba, to Intro będzie właściwie skończone. Zostanie tylko akapit "The structure is as follows", a właściwie połowa tego akapitu, bo o pierwszych sekcjach mówimy już wcześniej.

Nie mam pomysłu na raning egzampl. Na pewno go potrzebujemy?

PS. Rozdział o Erykerii też jest właściwie gotowy, poza dowodem rozstrzygalności istnienia ekwiwariantnych rozwiązań. Ten dowód zrobię jak już będą preliminarisy z reprezentacją zbiorów z atomami.

**Comment by szymtor** [comment]
Mi się podoba, jak dla mnie możesz mergować.

(Jak się przekonałeś się do brancha? Czyżby dlatego że Ci wczoraj zmieniłem
intro na masterze? hehe)

W IBC jest jeden mały detal techniczny:

jeżeli chcemy zredukować CFI query do IBC, to:

–albo redukujemy do hipergrafów ("torusów") i wtedy mamy color classes
rozmiaru k=2
–albo redukujemy do grafów CFI i wtedy mamy color classes rozmiaru
2 i 4 (czyli k=4).

Dlatego pisałem ogólniej o strukturach relacyjnych w definicji IBC,
ale to było faktycznie zamieszanie. Lepiej pisać tylko o grafach, ale wtedy
musi być k=4.

2015-01-06 12:51 GMT+01:00 bklin <notifications@github.com>:
